"""
Django settings for elastic_demo project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# General Settings
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.getenv("DEBUG", "False") == "True"  # Set DEBUG=False for production
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-@hc0x+a$*xe*nl@p!us2dz5sc385!7f8m5fnc914z!k9w^m7nw")
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")  # Use "*" for testing; restrict for production

# Cloud Run Port (default to 8080)
PORT = os.getenv("PORT", "8000")  # Default to 8000 if not provided

# Application Definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'elasticapp',
    'rest_framework',
    'corsheaders',  # Ensure CORS headers are added
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add CORS middleware before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'elastic_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'elastic_demo.wsgi.application'

# Database Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Elasticsearch Configuration
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': "https://03016c314ffa48fe975485dac5b90d53.us-central1.gcp.cloud.es.io:443",
        'api_key': "M2l0cGI1TUJ0ZUxxOTJBZ0UxdkE6OHI4QW9pOWJTR2FMQ2J6YmFLVS1JUQ=="
        # (
        #     # os.getenv("ELASTICSEARCH_USERNAME", "elastic"),
        #     os.getenv("ELASTICSEARCH_API_KEY", "M2l0cGI1TUJ0ZUxxOTJBZ0UxdkE6OHI4QW9pOWJTR2FMQ2J6YmFLVS1JUQ==")
        # )
    }
}

# Password Validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static Files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000",  # Local Frontend
    "http://localhost:3000",
    "https://lyrics-search-frontend-572081148214.us-central1.run.app",  # Deployed frontend
]

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:3000",  # Local Frontend
    "http://localhost:3000",
    "https://lyrics-search-frontend-572081148214.us-central1.run.app",  # Deployed frontend
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'